# Generated by Django 5.2.17 on 2026-10-05 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scorecard',
            name='uniq_scorecard_intern_week',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='portal.companyprofile'),
        ),
        migrations.AddConstraint(
            model_name='scorecard',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('intern', 'week_start'), name='uniq_scorecard_intern_week'),
        ),
        migrations.AddConstraint(
            model_name='scorecard',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'intern', 'week_start'), name='uniq_company_scorecard_intern_week'),
        ),
    ]
