# Generated by Django 5.2.17 on 2026-10-07 15:52

import django.db.models.deletion
import portal.validators
from django.conf import settings
from django.db import migrations, models


def create_default_requirements(apps, schema_editor):
    InternProfile = apps.get_model("portal", "InternProfile")
    OJTRequirement = apps.get_model("portal", "OJTRequirement")
    database = schema_editor.connection.alias
    defaults = (
        ("school", "Endorsement / recommendation letter", "A letter from your OJT coordinator or department head endorsing you for training.", True),
        ("school", "School–HTE Memorandum of Agreement (MOA)", "The agreement between your school and host training establishment.", True),
        ("school", "Certificate of Enrollment / Registration (COR)", "Proof of enrollment in the designated OJT or practicum subject.", True),
        ("school", "Transcript of Records / evaluation of grades", "Your school record showing that you meet the program prerequisites.", True),
        ("school", "Student accident insurance", "Proof of active student accident insurance for your training period.", True),
        ("legal", "Notarized parent / guardian consent and waiver", "The notarized consent and waiver required by your school or host.", True),
        ("legal", "Medical certificate", "A certificate from a licensed clinic or physician confirming fitness for training.", True),
        ("legal", "Barangay, police, or NBI clearance", "Submit a clearance only if requested by your school or host.", False),
        ("legal", "Government-issued ID / tax or social-security document", "Submit only the documents requested by your host; do not upload unrequested numbers.", False),
        ("application", "Resume / CV", "Your current resume or curriculum vitae.", False),
        ("application", "Cover letter / letter of intent", "A letter describing your interest in the placement.", False),
        ("application", "Portfolio", "A portfolio of relevant work, if requested for your field.", False),
        ("role_specific", "Drug test / laboratory exams", "Required only for applicable roles or when requested by your host.", False),
    )
    rows = []
    for intern in InternProfile.objects.using(database).all().iterator():
        rows.extend(
            OJTRequirement(
                intern_id=intern.pk,
                category=category,
                title=title,
                description=description,
                is_required=is_required,
            )
            for category, title, description, is_required in defaults
        )
    OJTRequirement.objects.using(database).bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_split_attendance_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OJTRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('school', 'School and academic'), ('legal', 'Legal and health'), ('application', 'Application'), ('role_specific', 'Company or role-specific')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, upload_to='ojt_requirements/%Y/%m/', validators=[portal.validators.FileSizeAndTypeValidator()])),
                ('status', models.CharField(choices=[('not_submitted', 'Not submitted'), ('submitted', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Changes requested')], default='not_submitted', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojt_requirements', to='portal.internprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ojt_requirement_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category', 'title'),
                'constraints': [models.UniqueConstraint(fields=('intern', 'title'), name='uniq_ojt_requirement_intern_title')],
            },
        ),
        migrations.RunPython(create_default_requirements, migrations.RunPython.noop),
    ]
