# Generated by Django 5.2.17 on 2026-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_ojt_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='external_host',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='placement_type',
            field=models.CharField(choices=[('platform', 'Company using Fieldwork'), ('external', 'External company (not using Fieldwork)')], default='platform', max_length=12),
        ),
    ]
