# Generated by Django 5.2.17 on 2026-10-07 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_intern_placement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('accomplishments', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Awaiting admin review'), ('reviewed', 'Reviewed'), ('changes_requested', 'Changes requested')], default='submitted', max_length=20)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='portal.internprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-work_date',),
                'constraints': [models.UniqueConstraint(fields=('intern', 'work_date'), name='uniq_daily_report_intern_day')],
            },
        ),
    ]
