# Generated by Django 5.2.17 on 2026-10-08 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_daily_intern_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='ojtrequirement',
            name='uniq_ojt_requirement_intern_title',
        ),
        migrations.AddField(
            model_name='ojtrequirement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ojt_documents', to='portal.companyprofile'),
        ),
        migrations.AddConstraint(
            model_name='ojtrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('intern', 'title'), name='uniq_ojt_baseline_requirement_intern_title'),
        ),
        migrations.AddConstraint(
            model_name='ojtrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('intern', 'company', 'title'), name='uniq_ojt_company_requirement_intern_title'),
        ),
        migrations.AddField(
            model_name='companyrequirement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='portal.companyprofile'),
        ),
        migrations.AddConstraint(
            model_name='companyrequirement',
            constraint=models.UniqueConstraint(fields=('company', 'title'), name='uniq_company_requirement_title'),
        ),
    ]
