# Generated by Django 5.2.17 on 2026-10-08 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_companyrequirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='clock_in_face_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='clock_in_face_status',
            field=models.CharField(choices=[('not_attempted', 'Not attempted'), ('not_captured', 'No camera image'), ('not_enrolled', 'No face enrollment'), ('matched', 'Match candidate'), ('not_matched', 'No match candidate'), ('unavailable', 'Could not check'), ('error', 'Check error')], default='not_attempted', max_length=16),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='clock_out_face_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='clock_out_face_status',
            field=models.CharField(choices=[('not_attempted', 'Not attempted'), ('not_captured', 'No camera image'), ('not_enrolled', 'No face enrollment'), ('matched', 'Match candidate'), ('not_matched', 'No match candidate'), ('unavailable', 'Could not check'), ('error', 'Check error')], default='not_attempted', max_length=16),
        ),
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_embedding', models.BinaryField()),
                ('consent_confirmed_at', models.DateTimeField()),
                ('consent_text_version', models.CharField(default='v1', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_enrollment', to='portal.internprofile')),
            ],
        ),
    ]
