# Generated by Django 5.2.17 on 2026-10-09 00:36

import django.db.models.deletion
import django.utils.timezone
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_attendancelog_clock_in_face_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='clock_in_face_status',
            field=models.CharField(choices=[('not_attempted', 'Not attempted'), ('not_captured', 'No camera image'), ('not_enrolled', 'No face enrollment'), ('consent_required', 'Updated consent required'), ('matched', 'Match candidate'), ('not_matched', 'No match candidate'), ('unavailable', 'Could not check'), ('error', 'Check error')], default='not_attempted', max_length=16),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='clock_out_face_status',
            field=models.CharField(choices=[('not_attempted', 'Not attempted'), ('not_captured', 'No camera image'), ('not_enrolled', 'No face enrollment'), ('consent_required', 'Updated consent required'), ('matched', 'Match candidate'), ('not_matched', 'No match candidate'), ('unavailable', 'Could not check'), ('error', 'Check error')], default='not_attempted', max_length=16),
        ),
        migrations.AlterField(
            model_name='faceenrollment',
            name='consent_text_version',
            field=models.CharField(default='v2', max_length=16),
        ),
        migrations.CreateModel(
            name='AttendanceFaceCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('time_in', 'Time in'), ('time_out', 'Time out')], max_length=8)),
                ('face_status', models.CharField(choices=[('not_attempted', 'Not attempted'), ('not_captured', 'No camera image'), ('not_enrolled', 'No face enrollment'), ('consent_required', 'Updated consent required'), ('matched', 'Match candidate'), ('not_matched', 'No match candidate'), ('unavailable', 'Could not check'), ('error', 'Check error')], max_length=16)),
                ('face_score', models.FloatField(blank=True, null=True)),
                ('encrypted_image', models.BinaryField(blank=True, null=True)),
                ('image_expires_at', models.DateTimeField(default=portal.models.face_capture_image_expiry)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('review_status', models.CharField(choices=[('not_required', 'No exception review required'), ('pending', 'Awaiting company/admin review'), ('approved', 'Exception approved'), ('rejected', 'Exception rejected')], default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_captures', to='portal.attendancelog')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_face_captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
    ]
