# Generated by Django 5.2.17 on 2026-10-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_attendancelog_clock_in_face_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancefacecapture',
            name='review_status',
            field=models.CharField(choices=[('not_required', 'No approval required'), ('pending', 'Awaiting company/admin approval'), ('approved', 'Approved by company/admin'), ('rejected', 'Rejected by company/admin')], default='pending', max_length=12),
        ),
    ]
