services:
  - type: web
    name: django-ims
    runtime: python
    buildCommand: bash build.sh
    startCommand: "DJANGO_SETTINGS_MODULE=django_ims.settings gunicorn django_ims.wsgi:application --bind 0.0.0.0:${PORT:-10000}"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DJANGO_SETTINGS_MODULE
        value: django_ims.settings
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: fieldwork-internship.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-ims-db
          property: connectionString

databases:
  - name: django-ims-db
    plan: free